// AUTH
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNOUT_USER = "SIGNOUTUSER";
export const SIGNOUT_ERROR = "SIGNOUTERROR";

// WATCHLIST
export const ADD_WATCHLIST_SUCCESS = "ADD_WATCHLIST_SUCCESS";
export const ADD_WATCHLIST_REQUEST = "ADD_WATCHLIST_REQUEST";
export const ADD_WATCHLIST_ERROR = "ADD_WATCHLIST_ERROR";
export const REMOVE_WATCHLIST_SUCCESS = "REMOVE_WATCHLIST_SUCCESS";
export const REMOVE_WATCHLIST_REQUEST = "REMOVE_WATCHLIST_REQUEST";
export const REMOVE_WATCHLIST_ERROR = "REMOVE_WATCHLIST_ERROR";
